# Use an official OpenJDK as the base image
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file from target directory to the container
COPY build/libs/*.war rest-0.0.1-SNAPSHOT.war

# Expose the application's port
EXPOSE 8080

# Command to run the application
ENTRYPOINT ["java", "-jar", "rest-0.0.1-SNAPSHOT.war"]

