version: '3.8'
services:
  app:
    image: prak5192/my-rest-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Learn@2025#

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Learn@2025#
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

